### ISSUE TITLE
running npm run dev does not generate a bundle.css

### ISSUE THREAD

**Issue by geocine** [sveltejs/template-custom-element#1]
I checked the demo you published on surge , there is a `bundle.css` also it is referenced on the `index.html` page. However running `npm run dev` does not produce that file. 

Is it needed or is it not used at all?

**Comment by Rich-Harris** [comment]
well spotted! i think it's just left over from when it was forked from the non-custom-element version — it uses Shadow DOM, which means the styles are baked into the element itself.
